# Generated by Django 5.2.11 on 2026-02-21 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('risk_band', models.CharField(default='Unknown', max_length=32)),
                ('breach_cost_low', models.PositiveIntegerField(default=0)),
                ('breach_cost_high', models.PositiveIntegerField(default=0)),
                ('downtime_days_low', models.PositiveIntegerField(default=0)),
                ('downtime_days_high', models.PositiveIntegerField(default=0)),
                ('insurance_readiness', models.CharField(choices=[('not_ready', 'Not Ready'), ('baseline', 'Baseline'), ('strong', 'Strong')], default='not_ready', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('email', 'Email'), ('backups', 'Backups'), ('devices', 'Devices'), ('training', 'Training'), ('data_access', 'Data Access'), ('planning', 'Planning'), ('payments', 'Payments')], max_length=32)),
                ('impact', models.CharField(max_length=255)),
                ('time_to_fix_minutes', models.PositiveIntegerField()),
                ('estimated_risk_reduction_pct', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('remediation_steps', models.JSONField(blank=True, default=list)),
                ('priority_score', models.FloatField(default=0.0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.assessment')),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('law_firm', 'Law firm'), ('medical', 'Medical practice'), ('startup', 'Startup / SaaS'), ('retail', 'Retail'), ('accounting', 'Accounting'), ('real_estate', 'Real estate'), ('consulting', 'Consulting / agency'), ('construction', 'Construction / contractor'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], default='other', max_length=32)),
                ('employee_count', models.PositiveIntegerField(default=1)),
                ('revenue_range', models.CharField(choices=[('lt_250k', '< $250k'), ('250k_1m', '$250k – $1M'), ('1m_5m', '$1M – $5M'), ('gt_5m', '> $5M')], default='lt_250k', max_length=32)),
                ('work_style', models.CharField(choices=[('in_office', 'Mostly in-office'), ('hybrid', 'Hybrid'), ('remote', 'Mostly remote')], default='in_office', max_length=32)),
                ('downtime_impact', models.CharField(choices=[('minor', 'Minor inconvenience'), ('lose_money', 'We miss deadlines / lose money'), ('cant_operate', "We can't operate")], default='lose_money', max_length=32)),
                ('primary_domain', models.CharField(max_length=255)),
                ('saas_stack', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.organization'),
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('dns_results', models.JSONField(blank=True, default=dict)),
                ('email_auth_results', models.JSONField(blank=True, default=dict)),
                ('tls_results', models.JSONField(blank=True, default=dict)),
                ('website_headers', models.JSONField(blank=True, default=dict)),
                ('overall_scan_status', models.CharField(default='pending', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
                ('top_risks', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('linked_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.assessment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to='core.organization')),
                ('linked_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.scanrun')),
            ],
        ),
    ]
