# Generated by Django 5.2.11 on 2026-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='checklist_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
