# Generated by Django 5.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_checklist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_assignee_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='OrgIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('trello', 'Trello'), ('jira', 'Jira')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orgintegration',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='core_orgintegration_org_provider_unique'),
        ),
    ]
