from django.urls import path
from .views import (
    APIRootView,
    AssessmentAISuggestionsView,
    AssessmentDetailView,
    AssessmentFindingsView,
    AssessmentStartView,
    AssessmentSubmitView,
    CreateTicketView,
    DashboardSummaryView,
    LoginView,
    MockGoogleWorkspaceTagView,
    OrganizationAssessmentsView,
    OrganizationDetailView,
    OrganizationGenerateReportView,
    OrganizationIntegrationsView,
    OrganizationListCreateView,
    OrganizationReportRunsView,
    OrganizationScanView,
    OrganizationScanRunsView,
    RegisterView,
    RunWorkflowView,
    SeedDemoView,
)

urlpatterns = [
    path("", APIRootView.as_view(), name="api-root"),
    path("auth/register", RegisterView.as_view(), name="auth-register"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("seed-demo", SeedDemoView.as_view(), name="seed-demo"),
    path("dashboard", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("orgs", OrganizationListCreateView.as_view(), name="org-list-create"),
    path("orgs/<int:pk>", OrganizationDetailView.as_view(), name="org-detail"),
    path("orgs/<int:pk>/scan", OrganizationScanView.as_view(), name="org-scan"),
    path("orgs/<int:pk>/generate-report", OrganizationGenerateReportView.as_view(), name="org-generate-report"),
    path("orgs/<int:pk>/assessments", OrganizationAssessmentsView.as_view(), name="org-assessments"),
    path("orgs/<int:pk>/scan-runs", OrganizationScanRunsView.as_view(), name="org-scan-runs"),
    path("orgs/<int:pk>/reports", OrganizationReportRunsView.as_view(), name="org-reports"),
    path("orgs/<int:pk>/integrations", OrganizationIntegrationsView.as_view(), name="org-integrations"),
    path("orgs/<int:pk>/create-ticket", CreateTicketView.as_view(), name="org-create-ticket"),
    path("orgs/<int:pk>/run-workflow", RunWorkflowView.as_view(), name="org-run-workflow"),
    path("orgs/<int:pk>/mock-google-workspace-tag", MockGoogleWorkspaceTagView.as_view(), name="org-mock-google-workspace-tag"),
    path("assessments/start", AssessmentStartView.as_view(), name="assessment-start"),
    path("assessments/<int:pk>/submit", AssessmentSubmitView.as_view(), name="assessment-submit"),
    path("assessments/<int:pk>", AssessmentDetailView.as_view(), name="assessment-detail"),
    path("assessments/<int:pk>/findings", AssessmentFindingsView.as_view(), name="assessment-findings"),
    path("assessments/<int:pk>/ai-suggestions", AssessmentAISuggestionsView.as_view(), name="assessment-ai-suggestions"),
]
